# Generated by Django 5.1.2 on 2024-12-21 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$4pL1GOsi2ik77q2OV6SK19$HPzYJL+8QxMLc0gar3VX7jhjq4buMKemwD/ZAf0T2OA=', max_length=128),
        ),
    ]
