# Generated by Django 5.1.2 on 2024-11-28 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='password_hash',
        ),
        migrations.AddField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$EKL9OwlQFtEjLgUUPfErYS$XCrA9NFjtEXZnt5chiW7ZDcX285jyKVsrqC6sgUmHgY=', max_length=128),
        ),
    ]
