# Generated by Django 5.1.2 on 2024-11-29 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0002_remove_admin_password_hash_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$9zWNW3RsWDe7dyLFJx6HZj$9d5ym1dyZ3XYmXNMSF7AFqwVo6BIeedjb5PFI89z7NA=', max_length=128),
        ),
    ]
