# Generated by Django 5.1.2 on 2024-12-21 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0003_alter_user_password_hash_activity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('revenue', models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$6ZvJScPJgPA2TfAc9QTBZP$GQ/TZusveHYJ7M+9KIwi1Xo3gEqJsV3p+ixEVogg7fE=', max_length=128),
        ),
    ]
