# Generated by Django 5.1.2 on 2024-11-29 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0003_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$v05MQ2M9ek5ESe9ngdyruC$v2pizvfT43tpEnNpeMulkN0lHWERSDICI6oXTjoBzeo=', max_length=128),
        ),
    ]
