# Generated by Django 5.1.2 on 2024-12-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0005_inventoryitem_category_alter_user_password_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$piGXs18IOOKvS5Q7ZzV71M$VxVnSqN3dMLqMLbkTo0sBTmSiX/7b5kiTJFXEBBz7RM=', max_length=128),
        ),
    ]
