# Generated by Django 5.1.2 on 2024-12-22 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0006_remove_order_order_id_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$dx7VJUZJOxcJeIarKfCr1j$c+qFyZK4z+VJQgXUPpgmuA5rrUwwbOXB+dsOZpjtvrA=', max_length=128),
        ),
    ]
