# Generated by Django 5.1.2 on 2024-12-22 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0007_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$oMwdPSGoYW0GsHy66T30Vm$CkVQPCerQILAoFqWVYTr62QxxlBYMXCnudgRToIqYys=', max_length=128),
        ),
    ]
