# Generated by Django 5.1.2 on 2024-12-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0008_alter_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$wzT4wBFPwPpD9XFtLyXZzF$3JLcN5Wt9mXyXjVYgbr+lwEWgPadsZ9xcAVX5315oE4=', max_length=128),
        ),
    ]
