# Generated by Django 5.1.2 on 2024-12-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0009_inventoryitem_image_url_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$cRLqg3njHO3b1Spl30ayU4$fJZyT1oFWKkWURmvivtjRIHUW4TebgGcIgRv5LW7RGk=', max_length=128),
        ),
    ]
