# Generated by Django 5.1.2 on 2024-12-23 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0010_alter_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.CharField(choices=[('1 PM', '1 PM'), ('5 PM', '5 PM')], default='1 PM', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Delivered', 'Delivered')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$xzt3Lf4PsqoUW9W9i77QPu$k8kT/VP1KcQANq0ngD7lanG+3TZHCGnDzEooFcBGA5E=', max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('customer', 'item')},
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBProject.inventoryitem')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='DBProject.order')),
            ],
        ),
    ]
