# Generated by Django 5.1.2 on 2024-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0011_order_delivery_time_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$py5OLZsjT2JOHbiIMrDXKD$tJLs/x3dFNLa6xgYydfi10mr1eey4xQd97esojYZhfM=', max_length=128),
        ),
    ]
