# Generated by Django 5.1.2 on 2024-12-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0012_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$f93AArwPpTxOZefWQKZTUA$ZR6mM4dNJEsCtFS+SMF+Hnzvg2Xii9w1MlabNN3tYtA=', max_length=128),
        ),
    ]
