# Generated by Django 5.1.2 on 2024-12-24 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0013_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$pin90vaMA5k05lCJurofMC$T0eI5sXTPAi4hbX026oT2Mcky9CPK5JgwflzJqsJID8=', max_length=128),
        ),
    ]
