# Generated by Django 5.1.2 on 2024-12-25 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0014_alter_user_password_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit-card', 'Credit Card'), ('easypaisa', 'EasyPaisa'), ('jazzcash', 'JazzCash'), ('cash-on-delivery', 'Cash on Delivery')], default='cash-on-delivery', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$FygwkK2JMULzdBnrkwxgT2$eQEUyzN2Qwpefye5jUqc0FBRCgHt8h4tjr/o27Jsna4=', max_length=128),
        ),
    ]
