# Generated by Django 5.1.2 on 2024-12-25 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DBProject', '0015_order_payment_method_alter_user_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_hash',
            field=models.CharField(default='pbkdf2_sha256$870000$TGXwDLxNP91p7JoSGtV8uy$X6xhDPM8TbLtkuqen1xW0KevATzxXGsonK/xEaGzRQE=', max_length=128),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DBProject.customer')),
            ],
        ),
    ]
